System.IO.IOException: The process cannot access the file because it is being used by another process.
Reading a file used by another process
https://stackoverflow.com/a/9760751

System.IO.IOException: The process cannot access the file '/app/b8mhr2fwolA.live_chat.json' because it is being used by another process.